import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-20 shrink-0 items-end rounded-lg bg-orange-400 p-4 md:h-52 w-full fixed">
          <Image
            src="/company.png"
            width={180}
            height={180}
            className="md:block hidden ml-5"
            alt="Screenshots of the dashboard project showing desktop version"
          />
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
